coverage:
   range: 50..90
   precision: 0

   notify:
      irc:  # Unfortunately this appears to be NYI. Waiting on codecov/support#60.
         default:
            server: "chat.freenode.net"

parsers:
   javascript:
      enable_partials: yes
